### ISSUE TITLE
Flyer drucken!

### ISSUE THREAD

**Issue by erictapen** [freifunk-tuebingen/tickets#1]
Der bereits vorhandene Flyer könnte mal gedruckt werden. Vorschlag: 200 Stück bei Flyer-Alarm

**Comment by erictapen** [comment]
Wichtig: Philipp wies völlig richtigerweise darauf hin, dass der Verein FFS eV da evtl Gelder für hat. Kontakt: vorstand@freifunk-stuttgart.de

**Comment by erictapen** [comment]
Jo, ist da eigentlich was passiert?

**Comment by Philhil** [comment]
Bisher gab es noch keine Mail.
Ich warte sehnsüchtig!

**Comment by alfonx** [comment]
So mich to do, so little time.

Aber danke für das Angebot und ich will das auch gerne annehmen.

Ich hoffe ich lasse bald was drücken  und würde euch dann die Rechnung schicken....

**Comment by alfonx** [comment]
Für den Gewerbeflyer aus Ticket #5  ist die Rechnung (71,79€) heute per Mail an den Stuttgarter Vorstand raus gegangen.

**Comment by alfonx** [comment]
DAnke
