### ISSUE TITLE
www.freifunk-tuebingen.de/sitemap.xml

### ISSUE THREAD

**Issue by alfonx** [freifunk-tuebingen/tickets#15]
http://www.freifunk-tuebingen.de/sitemap.xml soll bitte ein Sitemap haben die ich bei Bing und Google einreichen kann. Dafür soll grefel bitte ein entsprechendes Plugin installieren. Danke

**Comment by grefel** [comment]
Voila http://www.freifunk-tuebingen.de/sitemap.xml

Und settings gibt es hier: http://www.freifunk-tuebingen.de/wp-admin/options-general.php?page=google-sitemap-generator%2Fsitemap.php
