### ISSUE TITLE
Blogeintrag Weilheim Unterkunft

### ISSUE THREAD

**Issue by alfonx** [freifunk-tuebingen/tickets#17]
Der Blogeintrag kann was, weil da wurde eine spannende Richtfunkstrecke aufgebaut...

**Comment by erictapen** [comment]
Auf jeden Fall! Problem: Wie ausführlich beschreiben wir die Position der Relaystation?

**Comment by alfonx** [comment]
"eine Spiegel-Relaystation auf dem Schloßberg" .. das reicht

**Comment by alfonx** [comment]
http://www.freifunk-neckaralb.de/2016/11/03/richtfunk-in-weilheim/
