### ISSUE TITLE
Backup Wordpress

### ISSUE THREAD

**Issue by erictapen** [freifunk-tuebingen/tickets#18]
Wie läuft das eigentlich ab mit dem Backup des Wordpress? Ich würde gerne immer wenn es mir angeboten wird im Wordpress auf Update klicken können, ohne mir Sorgen zu machen.
@alfonx machst du zufällig sowieso ab und zu Backups von dem Server?

**Comment by alfonx** [comment]
+1 dafür, vor dem Ausfall schon an ein Backup zu denken ;-)

Ja, es gibt tägliche Backups der MySQL-Datenbank die zum WordPress gehört. Diese Backups werden 12 Tage gespeichert. Das ist nicht sehr viel - also ein Fehler/Löschen in der DB sollte nach max. 2 Tagen auffallen, sonst gibt es kein Backup. Wenn das so reicht, dann schließen...

**Comment by erictapen** [comment]
Alles klar, das reicht denke ich ;)
