### ISSUE TITLE
Überwachung von Tübinger Nodes mit Nagios

### ISSUE THREAD

**Issue by alfonx** [freifunk-tuebingen/tickets#20]
Auf Basis von Nagios und http://gw01.freifunk-stuttgart.de/map/json/global_map.json bzw. http://hg.albi.info/json/nodes.json  werden Nagios-Jobs angelegt (ein Job pro Node).

Das Nagios-Check-Skript lädt die JSON-Datei maximal einmal alle 333Sekunden runter und analysiert dann via Regex ob die Node auf online:true steht, bzw. ob lastseen nicht älter als 1h ist.

Bisher gibt es noch Probleme damit, dass die json-Datei nicht aktuell zu seinen scheint...

**Comment by alfonx** [comment]
Als dritte JSON Datei gibt es noch: http://karte.freifunk-stuttgart.de/json/nodes.json

Das aktuelle problem scheinen Zeitzonen zu sein....  Bei http://hg.albi.info/json/nodes.json kommen alle Daten in UTC... Ich bastel heute Abend weiter...

**Comment by Philhil** [comment]
Auf GW01 werden die JSON glaube nur jede 2 Minuten generiert. Ich hatte in meinem Script ein minimal Intervall von 5 Minuten um die Json Dateien zu syncen.

**Comment by alfonx** [comment]
Wir rufen aktuell alle 333s die Datei ab...

**Comment by alfonx** [comment]
Ich lege noch keine Hand für die Robustheit des Skripts ins Feuer, aber ist auf jeden Fal Beta. Hier ist der Code. https://github.com/freifunk-tuebingen/monitoring/blob/master/check_ffsnode_online.sh
Wenn das stabil ist, können sich Freifunk-Tübinger gerne einen Account auf meinen Nagios-Server kriegen, um auf das monitoring zu nutzen und per Email informiert zu werden...

Verbesserungen/Kommentare zum Skript erwünscht.. fork / pullrequests etc...

**Comment by alfonx** [comment]
Ja, eigentlich schien das jetzt zu laufen, ABER wenn wie jetzt http://hg.albi.info/json/nodes.json nicht erreichbar ist (failed: Connection refused) dann gehen hier alle Nodes auf CRITICAL. Besser wäre, wenn .. ja, wenn ... am besten passiert das nie ;-)

???

**Comment by alfonx** [comment]
Diese JSON-Datei http://karte.freifunk-stuttgart.de/json/nodesdb.json ist deutlich größer, enhält aber auch lastseen und nodename. Leider in einem ganz anderen Format, aber ich denke ich schreibe das noch so um, dass diese 2. URL mit ihrer Syntax als Fallback benutzt wird, wenn die erste URL down ist....

**Comment by alfonx** [comment]
http://karte.freifunk-stuttgart.de/json/nodes.json wird als Fallback verwendet, wenn hg.albi.info Probleme macht. Mal beobachten...

**Comment by erictapen** [comment]
Super ey!

**Comment by alfonx** [comment]
das klappt jetzt ! Wer seine node überwacht haben will (email wenn XX stunden offline) dann bei Stefan@freifunk-tuebingenpunktde melden
