### ISSUE TITLE
Über uns

### ISSUE THREAD

**Issue by erictapen** [freifunk-tuebingen/tickets#3]
Wir brauchen einen Artikel, der uns auf der Website vorstellt.
- Maximal 200 Wörter
- Freifunk ist 
  - toll
  - vernetzt Menschen
  - ermöglicht gesellschaftliche Teilhabe
  - Verhindert, dass das Internet böse wird
- Evtl Sprechstundenzeiten
- Wir sind FFS untergeordnet, Link zu FFS
- Drei-Vier Gesichter mit Namen und Kontakt
- Jeder schreibt einen Text über sich, am Ende der Woche werden alle Texte zusammen gemergt.

**Comment by alfonx** [comment]
Ich habe mal was angefangen. Das Format und alles muss nicht so bleiben.
http://www.freifunk-tuebingen.de/uber-uns/
Evtl. habe ich jetzt auch zu "Über uns" geschrieben, was eigentlich besser zu "Kontakt" soll? Es ist ein Anfang...

**Comment by erictapen** [comment]
Hab mal was geschrieben, spreche da aber ziemlich viel für andere. Feedback erbeten! Ist schon online, was ich aber bei der bisherigen Popularität der Seite verschmerzbar finde.

> Wir sind ein kleiner Haufen Tübinger, die in der Universitätsstadt die Idee freier Netzwerke voranbringen wollen. Wir glauben, dass freie Netze empowern, Gemeinschaft schaffen und für Technologie begeistern können.
> 
> Freifunk Tübingen ist keine eigenständige Freifunk-Community. Für Infos über Freifunk und Partizipation daran ist der Freifunk Stuttgart e.V. der richtige Ansprechpartner.
> 
> Du bist bei uns richtig, wenn Du in Tübingen Teil des Netzwerkes werden willst, dir aber das Know-How oder die richtigen Kontakte fehlen. Gerne helfen wir auch bei Installationen im öffentlichen Raum, in denen wir schon eine gewisse Erfahrung vorzuweisen haben. Siehe dazu auch unseren Blog und unsere Seite auf Github.

**Comment by erictapen** [comment]
Okay ich habe es mir nochmal mit Abstand durchgelesen und finde es okay.
