### ISSUE TITLE
Gewerbeflyer ("WLAN für ihr GEWERBE") entwerfen und drucken

### ISSUE THREAD

**Issue by erictapen** [freifunk-tuebingen/tickets#5]
- Ihre Gäste wollen freies WLAN
- FF kostet nur einmalig Geld

**Comment by Philhil** [comment]
Ideen und Vorlagen: https://wiki.freifunk-stuttgart.net/infomaterial:flyer:start

**Comment by alfonx** [comment]
Ein "WLAN für ihr GEWERBE" Flyer liegt gedruckt vor mir. Das Ticket schließen wenn die Dokumente des Flyers im Reporsitory liegen und hier verlinkt sind.

**Comment by alfonx** [comment]
Flyer liegt in GIT: https://github.com/freifunk-tuebingen/flyer/blob/master/2016-11%20Flyer_DIN_lang_Gewerbe.pdf
