### ISSUE TITLE
Wordpress Redakteur Accounts

### ISSUE THREAD

**Issue by erictapen** [freifunk-tuebingen/tickets#6]
Für alle!!!

**Comment by Likedeeler** [comment]
REMINDER:
. . .  Uuund? Wann kommen die?
;-)

**Comment by alfonx** [comment]
Dierks Redakteuraccount sollte per Email gerade rusgegangen sein.
Die anderen die Mitschreiben wollen/sollen bitte Vorname + Nachname + Email an stefan@freifung-tue...de schicken...
